name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/MicroserviceItem/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Check the current directory
        run: pwd
      - name: List all files
        run: ls -R /home/runner/work/AppPrueba/AppPrueba

      - name: Build with Maven
        run: mvn -f MicroserviceItem/pom.xml clean install -DskipTests=false  # Ejecuta Maven con la ruta completa
