name: Spring Boot

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Valida codigo
        uses: actions/checkout@v4.2.2

      - name: configura JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build 
        working-directory: ./AppPrueba/AppPrueba/MicroserviceItem
        run: mvn clean install -DskipTests=false
        
  
