name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: List directory contents
        run: ls -R
        
      - name: Build with Maven
        working-directory: /home/runner/work/AppPrueba/AppPrueba/MicroserviceItem/MicroserviceItem
        run: mvn clean install -DskipTests=false 
